--CREATE DATABASE TodoList;

--CREATE TABLE Userof(
--Id int PRIMARY KEY IDENTITY(1,1),
--Email NVARCHAR(50) NOT NULL,
--Password NVARCHAR(25) NOT NULL,
--);

--CREATE TABLE TodoItem(
--Id int PRIMARY KEY IDENTITY(1,1),
--Description NVARCHAR(100) NOT NULL,
--DueDate DATE NOT NULL,
--Complete BIT NOT NULL,
--IdNetUsers INT FOREIGN KEY REFERENCES ToDoItem(Id),
--);